[chains.ethereum]
chain_id = 1
rpc_url = "https://reth-ethereum.ithaca.xyz/rpc"

[[chains.ethereum.tokens]]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
decimals = 6
slug = "usdc"

[[chains.ethereum.tokens]]
address = "0x98C23E9d8f34FEFb1B7BD6a91B7FF122F4e16F5c"
decimals = 18
slug = "aave_ethereum_usdc"

[[chains.ethereum.tokens]]
address = "0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72"
decimals = 18
slug = "ens"

[[chains.ethereum.tokens]]
address = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
decimals = 18
slug = "weth"

[[chains.ethereum.trackers.fixed]]
token_in = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
token_out = "fiat:usdc"
fixed_rate = 1.0

[[chains.ethereum.trackers.erc4626]]
vault_address = "0x0c6aec603d48eBf1cECc7b247a2c3DA08b398DC1"

[chains.ethereum.trackers.uniswap_v2]
factory_address = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"

# wETH/ENS
[[chains.ethereum.trackers.uniswap_v2.pairs]]
pair_address = "0xB87b65Dacc6171B3ca8c4A934601d0FcB6c61049"

# stEth/wETH
[[chains.ethereum.trackers.uniswap_v2.pairs]]
pair_address = "0x4028DAAC072e492d34a3Afdbef0ba7e35D8b55C4"

# wBTC/USDC
[[chains.ethereum.trackers.uniswap_v3.pools]]
pool_address = "0x99ac8ca7087fa4a2a1fb6357269965a2014abc35"

# Aave/USDC
[[chains.ethereum.trackers.uniswap_v3.pools]]
pool_address = "0xdceaf5d0e5e0db9596a47c0c4120654e80b1d706"

# USDC/wETH
[[chains.ethereum.trackers.uniswap_v3.pools]]
pool_address = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"

# xAUT/USDT
[[chains.ethereum.trackers.uniswap_v3.pools]]
pool_address = "0x6546055f46e866a4b9a4a13e81273e3152bae5da"

[[chains.ethereum.trackers.uniswap_v3.pools]]
token_in = "0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c"
token_out = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
fee = 500

[[chains.ethereum.trackers.uniswap_v3.pools]]
token_in = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
token_out = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
fee = 500
